# Generated by Django 3.2.8 on 2021-12-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='valid_form',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
