# Generated by Django 3.2.8 on 2021-10-22 10:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Karusel',
                'verbose_name_plural': 'Karusellar',
            },
        ),
        migrations.CreateModel(
            name='MineralResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('button_txt', models.CharField(max_length=100)),
                ('button_link', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_item', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mineral resurs bazasi',
                'verbose_name_plural': 'Mineral resurslar bazasi',
            },
        ),
        migrations.CreateModel(
            name='TwoMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=200)),
                ('button_txt', models.CharField(max_length=100)),
                ('button_link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Xarita',
                'verbose_name_plural': 'Xarita',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('child_items', models.ManyToManyField(related_name='navitems', to='mainAPI.NavbarItem', verbose_name='child_item')),
            ],
            options={
                'verbose_name': 'Navbar elementi',
                'verbose_name_plural': 'Navbar elementlari',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('social_media', models.ImageField(upload_to='')),
                ('social_media_link', models.CharField(max_length=255)),
                ('sub_title', models.ManyToManyField(to='mainAPI.NavbarItem')),
            ],
        ),
    ]
