# Generated by Django 3.2.8 on 2021-12-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyTasks',
        ),
    ]
