# Generated by Django 3.2.8 on 2021-12-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationloc',
            name='dist',
            field=models.CharField(choices=[], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='applicationloc',
            name='raw_material',
            field=models.CharField(choices=[], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='applicationloc',
            name='region',
            field=models.CharField(choices=[], max_length=250, null=True),
        ),
    ]
