# Generated by Django 3.2.8 on 2021-10-22 10:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0002_auto_20211022_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTasksItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='navbaritem',
            options={},
        ),
        migrations.CreateModel(
            name='CompanyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company_tasks_items', models.ManyToManyField(related_name='tasksitems', to='mainAPI.CompanyTasksItems', verbose_name='child_item')),
            ],
            options={
                'verbose_name': 'Asosiy vazifa',
                'verbose_name_plural': 'Asosiy vazifalar',
            },
        ),
    ]
