# Generated by Django 3.2.8 on 2021-11-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0003_auto_20211118_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationloc',
            name='dist',
            field=models.CharField(choices=[('Jonboy', 'Jonboy')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='applicationloc',
            name='raw_material',
            field=models.CharField(choices=[('Oltin', 'Oltin')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='applicationloc',
            name='region',
            field=models.CharField(choices=[('Samarqand', 'Samarqand')], max_length=250, null=True),
        ),
    ]
