# Generated by Django 3.2.8 on 2021-10-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0004_auto_20211022_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditory',
            options={'verbose_name': 'Maqsadli auditoriya', 'verbose_name_plural': 'Maqsadli auditoriya'},
        ),
        migrations.RemoveField(
            model_name='auditory',
            name='title',
        ),
    ]
