# Generated by Django 3.2.8 on 2021-11-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0004_auto_20211127_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
