# Generated by Django 3.2.8 on 2021-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0005_auto_20211022_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155)),
                ('info', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimalar',
            },
        ),
    ]
