# Generated by Django 3.2.8 on 2021-10-22 11:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0006_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Loyiha hujjatlarini ekspertizalari',
                'verbose_name_plural': 'Loyiha hujjatlarini ekspertizasi',
            },
        ),
    ]
