# Generated by Django 3.2.8 on 2021-10-23 05:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0008_youthunion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': "Geologik ma'lumotlar to'plami",
                'verbose_name_plural': "Geologik ma'lumotlar to'plami",
            },
        ),
        migrations.CreateModel(
            name='ResourceBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=200)),
                ('excel_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Mineral resurslar bazasi',
                'verbose_name_plural': 'Mineral resurslar bazasi',
            },
        ),
    ]
