# Generated by Django 3.2.8 on 2021-10-23 06:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0009_geoinfo_resourcebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaptersItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': "Bo'limlar (Elem)",
                'verbose_name_plural': "Bo'limlar (Elem)",
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(blank=True, max_length=150)),
                ('chapter_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainAPI.chaptersitems', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name_plural': "Bo'limlar",
            },
        ),
    ]
