# Generated by Django 3.2.8 on 2021-10-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0010_chapters_chaptersitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Manzil va telefon',
                'verbose_name_plural': 'Manzil va telefon',
            },
        ),
    ]
