# Generated by Django 3.2.8 on 2021-11-02 04:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0011_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('text', ckeditor.fields.RichTextField()),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Qaror',
                'verbose_name_plural': 'Qarorlar',
            },
        ),
    ]
