# Generated by Django 3.2.8 on 2021-11-02 04:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0012_laws'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Hisobot olish uchun masullarning aloqalari',
                'verbose_name_plural': 'Hisobot olish uchun masullarning aloqalari',
            },
        ),
        migrations.CreateModel(
            name='ReportAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Hisobotlarni qabul qilish',
                'verbose_name_plural': 'Hisobotlarni qabul qilish',
            },
        ),
    ]
