# Generated by Django 3.2.8 on 2021-11-02 05:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0013_profconnections_reportacceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Universitet tadqiqotlari',
                'verbose_name_plural': 'Universitet tadqiqotlari',
            },
        ),
    ]
