# Generated by Django 3.2.8 on 2021-11-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0016_excel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('condition_a_b_c1', models.CharField(max_length=155)),
                ('condition_a_b_c2', models.CharField(max_length=155)),
                ('condition_c2', models.IntegerField()),
                ('exploitation', models.CharField(max_length=255)),
                ('absorption_level', models.CharField(default='default', max_length=255)),
                ('number_explot', models.CharField(max_length=155)),
                ('license', models.DateField()),
                ('prod_quantity', models.FloatField()),
                ('affiliation', models.CharField(max_length=255)),
                ('affirmation_year', models.CharField(max_length=155)),
                ('protocol_num', models.IntegerField()),
                ('raw_material', models.CharField(max_length=155)),
                ('region', models.CharField(max_length=155)),
                ('dist', models.CharField(max_length=155)),
            ],
        ),
        migrations.DeleteModel(
            name='Excel',
        ),
    ]
