# Generated by Django 3.2.8 on 2021-11-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0017_auto_20211103_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelform',
            options={'verbose_name': 'Excel форма', 'verbose_name_plural': 'Excel формалап'},
        ),
        migrations.AlterField(
            model_name='excelform',
            name='absorption_level',
            field=models.CharField(max_length=255),
        ),
    ]
