# Generated by Django 3.2.8 on 2021-11-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0019_auto_20211103_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('excel_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Буғалтерия хисоботи',
                'verbose_name_plural': 'Буғалтерия хисоботлари',
            },
        ),
        migrations.AlterModelOptions(
            name='carouselnews',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Каруселлар'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': 'Футер'},
        ),
        migrations.AlterModelOptions(
            name='laws',
            options={'verbose_name': 'Қарорлар', 'verbose_name_plural': 'Қарорлар'},
        ),
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name': 'Навбар (эл)', 'verbose_name_plural': 'Навбар (эл)'},
        ),
        migrations.AlterModelOptions(
            name='navbaritem',
            options={'verbose_name': 'Навбар (эл)', 'verbose_name_plural': 'Навбар (эл)'},
        ),
    ]
