# Generated by Django 3.2.8 on 2021-11-14 08:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0020_auto_20211113_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MFO_number', models.IntegerField()),
                ('account_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Хизмат кўрсатувчи банк бўйича маълумотлар',
                'verbose_name_plural': 'Хизмат кўрсатувчи банк бўйича маълумотлар',
            },
        ),
        migrations.CreateModel(
            name='Businessman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stir', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('ifut', models.IntegerField()),
                ('ceo_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тадбиркор',
                'verbose_name_plural': 'Тадбиркор',
            },
        ),
        migrations.CreateModel(
            name='MineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Кон ҳақида',
                'verbose_name_plural': 'Кон ҳақида',
            },
        ),
        migrations.CreateModel(
            name='ApplicationLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_phone', models.CharField(max_length=155)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainAPI.excelform')),
            ],
            options={
                'verbose_name': 'Ариза берадиган жой тўғрисида маълумот',
                'verbose_name_plural': 'Ариза берадиган жой тўғрисида маълумот',
            },
        ),
    ]
