# Generated by Django 3.2.8 on 2021-11-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0021_applicationloc_bankinfo_businessman_mineinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationloc',
            name='details',
        ),
        migrations.AddField(
            model_name='applicationloc',
            name='region',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainAPI.excelform'),
        ),
    ]
