# Generated by Django 3.2.8 on 2021-11-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0022_auto_20211116_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationloc',
            name='region',
        ),
    ]
